package fr.noxodev.noxoclaim.commands;
import fr.noxodev.noxoclaim.NoxoClaim; import fr.noxodev.noxoclaim.gui.ClaimGui; import fr.noxodev.noxoclaim.models.*; import fr.noxodev.noxoclaim.managers.SelectionManager; import fr.noxodev.noxoclaim.utils.TeleportTask; import org.bukkit.*; import org.bukkit.command.*; import org.bukkit.entity.Player; import org.bukkit.inventory.*; import java.util.*;
public final class ClaimCommand implements CommandExecutor,TabCompleter {private final NoxoClaim p;public ClaimCommand(NoxoClaim p){this.p=p;}public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player x)){p.messages().send(s,"player-only");return true;}if(a.length==0){p.messages().send(x,"usage");return true;}switch(a[0].toLowerCase()){case "wand"->wand(x);case "gui"->new ClaimGui(p).open(x);case "create"->create(x);case "delete","remove"->delete(x);case "info"->info(x);case "trust","untrust"->trust(x,a);case "flags"->flags(x,a);case "list"->list(x);case "sethome"->sethome(x);case "home","tp"->home(x);default->p.messages().send(x,"usage");}return true;}
private void wand(Player x){ItemStack i=new ItemStack(Material.valueOf(p.getConfig().getString("wand.material","GOLDEN_SHOVEL")));var m=i.getItemMeta();m.setDisplayName("§bWand de claim");i.setItemMeta(m);x.getInventory().addItem(i);p.messages().send(x,"wand-given");}
private void create(Player x){SelectionManager.Selection s=p.selections().get(x.getUniqueId());if(s==null||s.first()==null||s.second()==null){p.messages().send(x,"selection-required");return;}if(!s.first().getWorld().equals(s.second().getWorld())){p.messages().send(x,"selection-required");return;}if(p.claims().owned(x.getUniqueId()).size()>=p.getConfig().getInt("claim.max-per-player",10)){p.messages().send(x,"selection-too-large");return;}Claim c=new Claim(UUID.randomUUID(),x.getUniqueId(),x.getWorld().getName(),s.first().getBlockX(),s.first().getBlockZ(),s.second().getBlockX(),s.second().getBlockZ());long size=c.size();if(size<p.getConfig().getLong("claim.min-size",25)){p.messages().send(x,"selection-too-small");return;}if(size>p.getConfig().getLong("claim.max-size",1000000)||p.claims().overlaps(c)){p.messages().send(x,"selection-too-large");return;}p.claims().add(c);p.selections().clear(x.getUniqueId());p.messages().send(x,"created");}
private void delete(Player x){Claim c=p.claims().at(x.getLocation());if(c==null){p.messages().send(x,"not-found");return;}if(!c.getOwner().equals(x.getUniqueId())&&!x.hasPermission("noxoclaim.admin")){p.messages().send(x,"not-owner");return;}p.claims().remove(c);p.messages().send(x,"deleted");}
private void info(Player x){Claim c=p.claims().at(x.getLocation());if(c==null){p.messages().send(x,"not-found");return;}x.sendMessage("§bClaim §f"+c.getId()+" §7| propriétaire: §f"+Bukkit.getOfflinePlayer(c.getOwner()).getName()+" §7| taille: §f"+c.size());}
private void trust(Player x,String[] a){Claim c=p.claims().at(x.getLocation());if(c==null){p.messages().send(x,"not-found");return;}if(!c.getOwner().equals(x.getUniqueId())){p.messages().send(x,"not-owner");return;}if(a.length<2){x.sendMessage("§c/claim trust|untrust <joueur>");return;}UUID u=Bukkit.getOfflinePlayer(a[1]).getUniqueId();if(a[0].equalsIgnoreCase("trust")){c.addMember(u);p.messages().send(x,"trusted");}else{c.removeMember(u);p.messages().send(x,"untrusted");}p.claims().save();}
private void flags(Player x,String[] a){Claim c=p.claims().at(x.getLocation());if(c==null){p.messages().send(x,"not-found");return;}if(a.length<2){c.getFlags().forEach((f,v)->x.sendMessage("§7"+f+" = "+v));return;}if(!c.getOwner().equals(x.getUniqueId())){p.messages().send(x,"not-owner");return;}try{ClaimFlag f=ClaimFlag.valueOf(a[1].toUpperCase());c.setFlag(f,a.length<3||Boolean.parseBoolean(a[2]));p.claims().save();}catch(IllegalArgumentException e){x.sendMessage("§cFlag inconnue.");}}
private void list(Player x){x.sendMessage("§bVos claims: §f"+p.claims().owned(x.getUniqueId()).size());p.claims().owned(x.getUniqueId()).forEach(c->x.sendMessage("§7- "+c.getId()+" §f"+c.size()+" blocs"));}
private void sethome(Player x){Claim c=p.claims().at(x.getLocation());if(c==null){p.messages().send(x,"not-found");return;}if(!c.getOwner().equals(x.getUniqueId())){p.messages().send(x,"not-owner");return;}c.setHome(x.getLocation());p.claims().save();x.sendMessage("§aHome du claim défini.");}
private void home(Player x){Claim c=p.claims().at(x.getLocation());if(c==null){p.messages().send(x,"not-found");return;}Location target=c.getHome()!=null?c.getHome():new Location(x.getWorld(),c.getMinX()+.5,x.getWorld().getHighestBlockYAt(c.getMinX(),c.getMinZ())+1,c.getMinZ()+.5);new TeleportTask(p,x,target,p.getConfig().getInt("teleport.delay-seconds",3),p.getConfig().getBoolean("teleport.cancel-on-move",true));}
public List<String> onTabComplete(CommandSender s,Command c,String a,String[] args){if(args.length==1)return List.of("wand","create","delete","info","trust","untrust","flags","list","gui","home","sethome");if(args.length==2&&args[0].equalsIgnoreCase("flags"))return Arrays.stream(ClaimFlag.values()).map(Enum::name).toList();return List.of();}}
