name: NoxoClaim
version: 1.2.0
main: fr.noxodev.noxoclaim.NoxoClaim
api-version: '26.1'
author: NoxoDEV
description: Système de claims simple et moderne pour Paper 26.1 et 26.2.
softdepend:
  - Vault
commands:
  claim:
    description: Ouvre le menu NoxoClaim
    usage: /claim
  chome:
    description: Ouvre tes claims et téléporte vers un claim nommé
    usage: /chome <nom|list>
  claimadmin:
    description: Administration des claims
    usage: /claimadmin <list|delete>
    permission: noxoclaim.admin
permissions:
  noxoclaim.admin: { default: op }
  noxoclaim.bypass: { default: op }
