name: NoxoClaim
version: 1.3.0
main: fr.noxodev.noxoclaim.NoxoClaim
api-version: '26.1'
author: NoxoDEV
description: Système de claims simple par chunks pour Paper 26.1 et 26.2.
softdepend:
  - Vault
commands:
  hclaim:
    description: Ouvre NoxoClaim ou gère le chunk actuel
    usage: /hclaim [list|info|flags|trust|untrust|help]
  uclaim:
    description: Retire le claim du chunk actuel
    usage: /uclaim
  map:
    description: Ouvre le menu NoxoClaim
    usage: /map
  claim:
    description: Alias de /hclaim
    usage: /claim
  chome:
    description: Ouvre tes claims et téléporte vers un claim nommé
    usage: /chome <nom|list>
  claimadmin:
    description: Administration des claims
    usage: /claimadmin <list|delete>
    permission: noxoclaim.admin
permissions:
  noxoclaim.admin: { default: op }
  noxoclaim.bypass: { default: op }
